version: '3.8'

services:
  app:
    build: .
    command: bash -c "python src/database.py && python src/main.py" # Run database setup then main app
    environment:
      DB_USER: ilan
      DB_PASSWORD: ayelet90
      DB_HOST: 192.168.0.236
      DB_PORT: 5432
      DB_NAME: music
    # volumes:
    #   - .:/app # Mount the current directory into the container for live development